[package]
name = "ron-poc"
version = "0.1.0"
authors = ["Walter Pearce <jaynus@gmail.com>"]
edition = "2018"

[dependencies]
ron = "0.4.2"
option_set = "0.1.2"
bitflags = "1.0.4"

serde = "1.0.89"
serde_json = "1.0.39"